---
title: "About"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error = FALSE, message = FALSE)

library(dplyr)
# devtools::install_github("privefl/googlesheets")
library(googlesheets)
# install.packages(c("leaflet", "DT"))
library(leaflet)
library(DT)
```

## R Workshop for the NMFS Economics and Human Dimensions Program

Some time ago, in preparation for the NMFS Social Science/Human Dimensions meeting, I was part of a group that was asked to prepare content for a possible "R for Social Scientists" workshop. The idea was to offer this workshop at the NMFS Social Science/Human Dimensions meeting. Although the in-person meeting has been canceled, our group has continued developing the content for the originally proposed R workshop. That content is available on GitHub for anyone to enjoy and will also form the basis for the virtual "R for Social Scientists" workshop which will take place via WebEx from Tuesday, September 22nd - Thursday, September 24th from 9 am - 12 :00pm PST(Pacific Time)/12 pm - 3 pm EST.

The basic condition I wanted to satisfy in developing this course was that every particpant be able to find at least one helpful/useful R nugget somewhere in this mix (the "nobody leaves empty-handed principle"). In hindsight, I heinously underestimated how difficult this would be. I sincerely hope all of you will find some value in the material assembled here....if you don't, just know that I tried.

--aaron

