---
title: "Discussion during Workshop"
output:
  html_document:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---


*Please click on the title to see the session description*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(htmltools)
library(here)
```


```{r}

#Discussion <- data.frame(read_csv("./R Workshop Detailed Schedule.csv", col_names = FALSE))
Discussion <- data.frame(read_csv("./R Workshop Discussion.csv", col_names = FALSE))
# Discussion <- data.frame(read_csv(here("R Workshop Detailed Schedule.csv"), col_names = FALSE))
names(Discussion)<-Discussion[2,]
Discussion<-Discussion[-c(1:2),]
Discussion$Authors<-""
Discussion$Notes0<-Discussion$Notes
Discussion0 <- Discussion


Discussion$Notes[is.na(Discussion$Notes)]<-""

aa<-strsplit(x = Discussion$Notes, split = "\n\n")
for (i in 1:length(aa)){
  if (length(aa[i][[1]])!=0) {
    for (ii in 1:length(aa[i][[1]])) {
      # if (grepl(pattern = "https://", x = aa[i][[1]][ii], ignore.case = T)) {
      #   bb<-strsplit(x = aa[i][[1]][ii], split = ": ")
      # if (grepl(pattern = ".html", x = aa[i][[1]][ii], ignore.case = T)) {
      #   htmlname<-strsplit(split = "/", x = bb[[1]][2])[[1]]
      #   download.file(url = bb[[1]][2], 
      #                 destfile = paste0(getwd(), "/les_", htmlname[length(htmlname)]))
      #   bb[[1]][2]<-paste0("les_", htmlname[length(htmlname)])
      # }
      #   # cc<-paste0('["', bb[[1]][1], '"] (', bb[[1]][2], '")')
      #   # cc<-paste0('<a href="', bb[[1]][2], '">', bb[[1]][1], '</a>')
      #   cc<-paste0('
      #   tags$p(""),
      #   tags$a(href="', bb[[1]][2], '", "', bb[[1]][1], '")')
      #   # cc<-paste0("![{",bb[[1]][2],"}]({",bb[[1]][1],"})")
      #   # aa[i][[1]][ii]<-paste0("<li>", cc, "</li>")
      # 
      #   aa[i][[1]][ii]<-cc#paste0('tags$li(', cc, ')')
      #   } else {
      
      aa[i][[1]][ii]<-gsub(pattern = '"', replacement = "'", x = aa[i][[1]][ii])
      # aa[i][[1]][ii]<-gsub(pattern = "'", replacement = "\\\'", x = aa[i][[1]][ii])
      
        cc<-paste0('tags$p("', aa[i][[1]][ii], '")')
        # cc<-paste0('<p>', ifelse(is.na(aa[i][[1]][ii]), "", aa[i][[1]][ii]), '</p>')
        # aa[i][[1]][ii]<-paste0("<li>", cc, "</li>")
        aa[i][[1]][ii]<-cc#paste0('tags$li(', cc, ')')
      # }
      
    }
      # aa[i][[1]]<-paste0("tags$div(",
  #                    paste(aa[i][[1]], collapse = " "),
  #                    ")")
    aa[i][[1]]<-paste0('tags$li(', paste(aa[i][[1]], collapse = ", "), ')')
    # aa[i][[1]]<-paste(aa[i][[1]], collapse = ", ")
  } else {
    aa[i][[1]]<-""
  }
  # aa[i][[1]]<-paste0("")
}
Discussion$Notes<-unlist(aa)
Discussion<-Discussion[,c("Date","Notes","Topic","Authors")]

program<-as_tibble(Discussion) #%>%


```

```{css}
.schedule {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.limit {
  width: 100%;
  padding: 5px 0 5px 0;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.left-date {
  width: 20%;
  float: left;
  text-align: left;
}

.center-title {
  width: 60%;
  float: left;
  text-align: left;
  font-size: 120%;
}

.right-authors {
  width: 20%;
  float: right;
  text-align: right;
}

.workshops {
  margin: 1em 1em 0 0;
}

.active {
  background-color: #333333;
  color: whitesmoke;
}

```

```{js}
function main() {
  $('.schedule').hide();
  $('.schedule').fadeIn(2000);
  $('.workshops').hide();
  $('.workshops-button').on('click', function() {
    $(this).next().slideToggle(400);
    $(this).toggleClass('active');
  });
}
 
$(document).ready(main);
```

## Tuesday, September 22, 2020

```{r}
program1<-program[grepl(pattern = "Tuesday, September 22, 2020", x = Discussion0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Topic']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)
```

