---
title: "Course Agenda (Pacific Time) and Lessons"
---

We are excited that you will be joining us for this workshop! Please fill out this [google form](https://docs.google.com/forms/d/e/1FAIpQLSd6yThLtJLjAICFzvOkPGoAou3aJcD-4s-7uhVFfQI3hVaoMQ/viewform?usp=sf_link) to let us know that you will be joining us. 

*Please click on the title to see the session description*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
Sys.setlocale("LC_TIME", "C")
library(htmltools)
```

```{r}
PreMaterial <- data.frame(read_csv("./R Workshop Video Links.csv", col_names = FALSE))
names(PreMaterial)<-PreMaterial[2,]
PreMaterial<-PreMaterial[-c(1:3),]
PreMaterial<-PreMaterial[!(is.na(PreMaterial$Topic)),]
PreMaterial0 <- PreMaterial

PreMaterial$NeedToKnow<-paste0("Importance Level: ",PreMaterial$`Importance Level`,"; 
                                Fun-ness: ", PreMaterial$`Fun-ness`, ";
                                Suggested For: ", PreMaterial$`Suggested for`)

PreMaterial$Notes<-gsub(pattern = '"', replacement = "'", x = PreMaterial$Notes)
PreMaterial$Notes0<-paste0('tags$li(', #paste(
                           paste0('tags$p("', PreMaterial$NeedToKnow, '"),'), 
                           ifelse(is.na(PreMaterial$Notes), "",
                                  paste0('tags$p("', PreMaterial$Notes, '"),')), 
                           paste0('tags$a(href="', PreMaterial$`Video Link`, '", "Video Link"),
                                  '), 
                           paste0('tags$a(href="', PreMaterial$Playlist, '", "Playlist Link")'),
                           # collapse = ", "), 
                           ')')



PreMaterial$NeedToKnow<-""
PreMaterial$Title<-paste0(PreMaterial$`Playlist Title`," - ", PreMaterial$Topic)
PreMaterial$Authors<-"Aaron Mamula"
PreMaterial<-data.frame(PreMaterial)
rownames(PreMaterial)<-1:nrow(PreMaterial)
```

```{css}
.schedule {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.limit {
  width: 100%;
  padding: 5px 0 5px 0;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.left-date {
  width: 20%;
  float: left;
  text-align: left;
}

.center-title {
  width: 60%;
  float: left;
  text-align: left;
  font-size: 120%;
}

.right-authors {
  width: 20%;
  float: right;
  text-align: right;
}

.workshops {
  margin: 1em 1em 0 0;
}

.active {
  background-color: #333333;
  color: whitesmoke;
}

```

```{js}
function main() {
  $('.schedule').hide();
  $('.schedule').fadeIn(2000);
  $('.workshops').hide();
  $('.workshops-button').on('click', function() {
    $(this).next().slideToggle(400);
    $(this).toggleClass('active');
  });
}
 
$(document).ready(main);
```

## Pre-Meeting Materials

```{r}
program1<-PreMaterial

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['NeedToKnow']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes0"]])) ) )
              # event[["Notes"]])
    )
  })
)
```

<br>

```{r}
# https://googledrive.tidyverse.org/
# https://docs.google.com/spreadsheets/d/1NkG331BZW_Q9PuzdhEgW5rB6vkLe0K_Dd1K3iFrAFNw/edit?usp=sharing
# drive_deauth()
# drive_auth()
# drive_download("R Workshop Detailed Schedule", type = "csv")

# Agenda <- data.frame(read_csv("../Agenda.csv"))

Agenda <- data.frame(read_csv("./R Workshop Detailed Schedule.csv", col_names = FALSE))
names(Agenda)<-Agenda[2,]
Agenda<-Agenda[-c(1:2),]
Agenda$Notes0<-Agenda$Notes
Agenda0 <- Agenda

not0<-c("", "??", NA)
Agenda$Date<-paste0(#Agenda$Date, " (", 
  Agenda$`Start Time (PT)`, "-", Agenda$`End Time (PT)`
  #, ")"
  )
Agenda$Title<-paste0(Agenda$`Course Segment`,
                     ifelse( ( Agenda$`Course Segment` == Agenda$Topics | 
                                 Agenda$`Course Segment` %in% not0 | 
                                 Agenda$Topics %in% not0 ), "", " - "), 
                     ifelse( ( Agenda$`Course Segment` == Agenda$Topics | 
                                 Agenda$Topics %in% not0 ), "", Agenda$Topics) )

Agenda$Authors<-paste0(ifelse(Agenda$Presenter %in% not0, "", paste0("Presenter: ", Agenda$Presenter)), #Presenter
                       ifelse((Agenda$`Chat/Q&A` %in% not0), "", "; "), # ; 
                       ifelse((Agenda$Presenter %in% not0), "", " "), # Space
                       ifelse(Agenda$Host %in% not0, "", paste0("Host: ", Agenda$Host)), # Host
                       ifelse((Agenda$`Chat/Q&A` %in% not0), "", "; "), # ; 
                       ifelse(Agenda$`Chat/Q&A` %in% not0, "", paste0("Help: ", Agenda$`Chat/Q&A`)) ) # Help

Agenda$Notes[is.na(Agenda$Notes)]<-""
# Agenda$Notes[1]<-'tags$a(href="www.rstudio.com", "Click here!")'
# Agenda$Notes[2]<-'<a href="www.rstudio.com">Click here!</a> '
# Agenda$Notes[3]<-'[Click here!](www.rstudio.com)'

aa<-strsplit(x = Agenda$Notes, split = "\n\n")
for (i in 1:length(aa)){
  if (length(aa[i][[1]])!=0) {
    for (ii in 1:length(aa[i][[1]])) {
      # dd<- aa[i][[1]][ii]
      if (grepl(pattern = "https://", x = aa[i][[1]][ii], ignore.case = T)) {
        bb<-strsplit(x = aa[i][[1]][ii], split = ": ")
        # cc<-paste0('["', bb[[1]][1], '"] (', bb[[1]][2], '")')
        # cc<-paste0('<a href="', bb[[1]][2], '">', bb[[1]][1], '</a>')
        cc<-paste0('tags$a(href="', bb[[1]][2], '", "', bb[[1]][1], '")')
        # cc<-paste0("![{",bb[[1]][2],"}]({",bb[[1]][1],"})")
        # aa[i][[1]][ii]<-paste0("<li>", cc, "</li>")
        aa[i][[1]][ii]<-cc#paste0('tags$li(', cc, ')')
      } else {
        cc<-paste0('tags$p("', aa[i][[1]][ii], '")')
        # cc<-paste0('<p>', ifelse(is.na(aa[i][[1]][ii]), "", aa[i][[1]][ii]), '</p>')
        # aa[i][[1]][ii]<-paste0("<li>", cc, "</li>")
        aa[i][[1]][ii]<-cc#paste0('tags$li(', cc, ')')

      }
    }
      # aa[i][[1]]<-paste0("tags$div(",
  #                    paste(aa[i][[1]], collapse = " "),
  #                    ")")
    aa[i][[1]]<-paste0('tags$li(', paste(aa[i][[1]], collapse = ", "), ')')
    # aa[i][[1]]<-paste(aa[i][[1]], collapse = ", ")
  } else {
    aa[i][[1]]<-""
  }
  # aa[i][[1]]<-paste0("")
}

Agenda$Notes<-unlist(aa)
# Agenda$Notes<-gsub(pattern = "//\", )
# Agenda$Notes<-gsub(pattern = "\\\\", replacement = "", x = Agenda$Notes)

Agenda<-Agenda[,c("Date","Notes","Title","Authors")]

# Agenda<-Agenda[1,]
# Agenda0<-Agenda0[1,]

program<-as_tibble(Agenda) #%>%
  # mutate(Date = dmy(Date))


#Come by to ask any questions you have about the course, content, or with specific questions about issues you have in your own analyses.

# stopifnot(all(wday(program$Date) == 5)) # Thursdays (begin with Sundays)
          
# program <- program %>%
  # arrange(Date) %>%
  # mutate(Date = format(Date, format = "%B %d, %Y"))
```


```{css}
.schedule {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.limit {
  width: 100%;
  padding: 5px 0 5px 0;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

# .workshops-button[data-workshops = "Tuesday, September 22, 2020"]:after {
#   padding: 0.75em 1.25em;
#   background-color: #cccccc;
#   opacity: 0.9;
#   width: auto;
#   color: red;
#   text-align: center;
#   overflow: auto;
# }



.left-date {
  width: 20%;
  float: left;
  text-align: left;
}

.center-title {
  width: 60%;
  float: left;
  text-align: left;
  font-size: 120%;
}

.right-authors {
  width: 20%;
  float: right;
  text-align: right;
}

.workshops {
  margin: 1em 1em 0 0;
}

.active {
  background-color: #333333;
  color: whitesmoke;
}

```

```{js}
function main() {
  $('.schedule').hide();
  $('.schedule').fadeIn(2000);
  $('.workshops').hide();
  $('.workshops-button').on('click', function() {
    $(this).next().slideToggle(400);
    $(this).toggleClass('active');
  });
}
 
$(document).ready(main);
```

## Tuesday, September 22, 2020

```{r}
program1<-program[grepl(pattern = "Tuesday, September 22, 2020", x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)
```

<br>


## Wednesday, September 23, 2020

```{r}
program1<-program[grepl(pattern = "Wednesday, September 23, 2020", x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button",
          div(class = "left-date",
              event[['Date']]),
          div(class = "center-title",
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)
```

<br>


## Thursday, September 24, 2020

```{r}
program1<-program[grepl(pattern = "Thursday, September 24, 2020", x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button",
          div(class = "left-date",
              event[['Date']]),
          div(class = "center-title",
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)
```

<br>


